### ISSUE TITLE
Set Exec download timeout parametric

### ISSUE THREAD

**Issue by blues-man** [biemond/biemond-wildfly#116]
Hi,
I'm using this module also to deploy also [Keycloak](http://keycloak.jboss.org/), just changing  $version and  $install_source, and everything is fine but it happens that sometimes download is slower thus Exec timeout expires. 

A possibile workaround now could be:

`
Exec["Download wildfly from ${install_source}"] {
       timeout => 1000
}
`

instead of setting global Exec timeout or modify wildfly module.

Maybe a $install_source_timeout in wildfly class constructor could help

**Comment by jairojunior** [comment]
Excellent.

I always wondered if this module would work with other JBoss family products (i.e. Middlewares that use the same JBoss architecture), it seemed feasible to work with Infinispan but it never got to production since we opted for an alternative product in my company.

It's a very simple change, I'll put in my backlog if you're not going for it.

https://github.com/biemond/biemond-wildfly/blob/master/manifests/install.pp#L17

**Comment by blues-man** [comment]
I can send a PR after running tests, it should be just adding it in `wildfly::params` and in the constructor, then using it in `wildfly::install`
By the way, I would share the correct mininum configuration change for Keycloak:

```
class { wildfly:
      version           =>  '1.7.0',
      install_source    => 'http://downloads.jboss.org/keycloak/1.7.0.Final/keycloak-1.7.0.Final.tar.gz',
      config            => 'standalone.xml'
 }
```

Since Wildfly typical `standalone-full.xml` isn't shipped here
