### ISSUE TITLE
New Release hosted on http not Deployed

### ISSUE THREAD

**Issue by LightAxe** [biemond/biemond-wildfly#140]
When deploying new releases (war files) to http, biemond-wildfly isn't triggering a redeployment of the WAR file to jboss.

(edit:  new releases of the same already deployed application, ie; a new build of the already-deployed ab.war)

I'm very much open to workarounds and discussion!

**Comment by jairojunior** [comment]
Just to give some background regarding deployment feature:

- It used to use puppet-archive to handle downloads, but some users have another archive module (.e.g camptocamp-archive) in their environments.
- Removed puppet-archive dependency and deployment was only able to handle file sources.
- Decided to bring simple http source back in a PR - but I do not really use since I'm puppet-archive user and mainly use archive::nexus

Now, I'm not sure weather your request is deployment responsibility or it should be managed by an external module:

    archive { '/tmp/myapp.war':
      source => 'http://',
    }
    ~>
    wildfly::deployment { 'myapp.war': }

So, do you think we should improve wildfly::deployment or completely remove remote sources? :smile:

**Comment by LightAxe** [comment]
Oh, great questions.

Ultimately, I'm trying to push from a TFS build server (Windows) to JBoss (Linux).  

Does archive::nexus support refreshing based on HTTP end changes?  Perhaps I'll investigate...

**Comment by jairojunior** [comment]
Don't know TFS, but archive uses md5 or sha1 to check if the file is new. You can hardcode the checksum in your manifests or use a remote checksum source (like I use for archive::nexus).

A simple way to achieve your expected result in a typical HTTP server would be to host both your Java Archive (JAR, WAR, EAR) alongside its correspondent .md5 ou .sha1 file.

More: https://forge.puppet.com/puppet/archive

I was just reading wget manpage and I think `wget -N` is able to detect server updates based on time stamping and maybe we would only need to change: https://github.com/biemond/biemond-wildfly/blob/master/manifests/deployment.pp#L49 from `require` to `subscribe` metaparameter. That's another alternative that probably worth a shot.

**Comment by LightAxe** [comment]
I'd vote removing remote sources after looking at this and thinking about it.  It can lead to confusion and doesn't *really* get you what you need.
