### ISSUE TITLE
Set a value to undefined?

### ISSUE THREAD

**Issue by LightAxe** [biemond/biemond-wildfly#198]
How do I set a value to undefined in a resource?

https://issues.jboss.org/browse/WFLY-3538

I've tried various versions of this:

```
  wildfly::resource { '/subsystem=ee/service=default-bindings':
    content   => {
      'datasource' => '',
    },
  }
```
```
  wildfly::resource { '/subsystem=ee/service=default-bindings':
    content   => {
      'datasource' => 'undefined',
    },
  }
```
```
  wildfly::resource { '/subsystem=ee/service=default-bindings':
    content   => {
      'datasource' => undef,
    },
  }
```
But none are actually setting the value to undefined, similar to ` /subsystem=ee/service=default-bindings:undefine-attribute(name=datasource)`

**Comment by LightAxe** [comment]
I also tried this:

 ```
 wildfly::cli { 'Remove default datasource':
    command => '/subsystem=ee/service=default-bindings:undefine-attribute(name=datasource)',
    unless  => "(result == undefined) of /subsystem=ee/service=default-bindings:read-attribute(name=datasource)",
  }
```

However, that turns into 'resource' => 'undefined' for the check statement, yet the actual results from the CLI are:

```
[standalone@localhost:9990 /] /subsystem=ee/service=default-bindings:read-attribute(name=datasource)
{
    "outcome" => "success",
    "result" => undefined
}
```

I haven't figured out how to get it to check for undefined in the () check; is it documented somewhere?

**Comment by LightAxe** [comment]
The raw packet result (I sniffed lo to see what was going back and forth) gave us a JSON object:
```
{"outcome" : "success", "result : null}
```

**Comment by jairojunior** [comment]
Interesting.

1) `wildfly::resource`  is always removing `undef` values: https://github.com/biemond/biemond-wildfly/blob/master/manifests/resource.pp#L28. But it will probably not work with `wildfly_resource` either as I am not assembling undefined-attribute operations. 😞 

2) `wildfly::cli` is not working cause API returns null instead of undefined as you pointed out in your last commentd.

Good news is that it's not hard to fix, just need to handle these different kinds of representations: `undef`, (Puppet), `undefined` (DMR) and `null` (JSON).

I'll work on this.

**Comment by jairojunior** [comment]
`wildfly::cli` is working for `undefined` comparisons now, you should be able to use the command you posted above.

Still need to change:

- `wildfly::resource` to introduce a new parameter to allow attributes to be undefined.
-  wildfly_resource to convert undef to nil.
- operation_request to convert undef to nil.

**Comment by jairojunior** [comment]
The changes above were made and it should be working right now, even for `wildfly::resource` using `undefine_attributes => true`.
