### ISSUE TITLE
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir 

### ISSUE THREAD

**Issue by josiasyoumbi** [biemond/biemond-wildfly#257]
I get an error when trying trying to apply this module.

on my   .pp

class { 'wildfly':
  version        => '8.2.1',
  install_source => 'http://download.jboss.org/wildfly/8.2.1.Final/wildfly-8.2.1.Final.tar.gz',
}

Error
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /var/cache/wget/wildfly-8.2.1.Final.tar.gz20181019-11672-ebumhh.lock (file: /etc/puppetlabs/code/environments/development/modules/wildfly/manifests/install.pp, line: 12)

**Comment by bparry02** [comment]
This issue is described in #191. Your system does not have `wget` installed, so it has not created the `/var/cache/wget` directory.

I recommend following [Jairo's suggestion](https://github.com/biemond/biemond-wildfly/issues/191#issuecomment-298631543) and setting your own `install_cache_dir` parameter on the wildfly class to a directory that exists.

**Comment by josiasyoumbi** [comment]
Thanks for the tip, it works now.
